{
 "title": "INFORMACIÓ GENERAL",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "usuari",
    "label": "Usuari",
    "query": "SELECT usuario FROM verse_payments WHERE \"timestamp\" >= ${__from:date:seconds} AND \"timestamp\" <= ${__to:date:seconds}"
   }
  ]
 },
 "panels": [
  { "title": "ESTADISTIQUES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL GASTAT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval),\n  sum(cantidad) AS \"Quantitat gastada\"\nFROM verse_payments\nWHERE\n  $__unixEpochFilter(\"timestamp\") AND\n  usuario = '$usuari'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "HORES JUGADES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval),\n  sum(cantidad)/2.5*60 AS \"Hores jugades\"\nFROM verse_payments\nWHERE\n  $__unixEpochFilter(\"timestamp\") AND\n  usuario = '$usuari'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pagaments al llarg del temps - Comparativa",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval),\n  sum(cantidad) AS \" \",\n  usuario\nFROM verse_payments\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nGROUP BY 1, 3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pagaments al llarg del temps",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval, 0),\n  sum(cantidad) AS \"Quantitat gastada\"\nFROM verse_payments\nWHERE\n  $__unixEpochFilter(\"timestamp\") AND\n  usuario = '$usuari'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "HISTORIAL DE PAGAMENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  usuario, cantidad\nFROM verse_payments\nWHERE\n  $__unixEpochFilter(\"timestamp\")\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}